### ISSUE TITLE
Lacking constraint on DB schemas

### ISSUE THREAD

**Issue by ddaws** [infinityCounter/QMVC#5]
The schools table schema lacks DB constraints. Ideally schemas are as explicit as possible about their constraints to prevent possible data corruptions.

https://github.com/infinityCounter/QMVC/blob/70d98fd56971b3b56d9fd95884223db0e0b54b53/application/install/national_school_registrar.sql#L31-L36

**Comment by infinityCounter** [comment]
Has been dropped from project due to rewrite. The primary purpose of the SQL script before was to prepare a database to be used in the demo application. Now that a native database interface solution has been dropped, this is no longer required.
