### ISSUE TITLE
Is autoloading required? 

### ISSUE THREAD

**Issue by ddaws** [infinityCounter/QMVC#6]
Autoloading is a potential vulnerability because it possibly unknown code executing on application initialization. Is this really required? How much effort would it be to explicitly bootstrap the environment to contain the classes we require? 

Autoloading occurs here https://github.com/infinityCounter/QMVC/blob/70d98fd56971b3b56d9fd95884223db0e0b54b53/public/index.php#L15-L17

Alternatively, what about creating a custom autoloader that can be used to whitelist classes for autoloading?

**Comment by infinityCounter** [comment]
All auto loading removed from project except for unit tests. Will consider a whitelist autoloader but closing for now.
